version: 2
jobs:
  lint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: swiftlint lint | tee swiftlint.txt
      - store_artifacts:
          path: swiftlint.txt
  danger:
    docker:
      - image: dantoml/danger:latest
    steps:
      - checkout
      - run: danger

workflows:
  version: 2
  build_test_lint:
    jobs:
      - lint
      - danger
